services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      elasticsearch:
        condition: service_healthy

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    # volumes:
    #   - ./backend:/app
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-u",
          "elastic:changeme",
          "-f",
          "http://localhost:9200/_cluster/health",
        ]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  esdata:
